### ISSUE TITLE
Fix the kernel module bricking the Linux kernel

### ISSUE THREAD

**Issue by CyntexMore** [CyntexMore/tmx-ffb-driver#12]
Fix the kernel module bricking the Linux kernel

**Comment by vb2007** [comment]
Close the issue, that's intended functionality on an average linux driver.

**Comment by CyntexMore** [comment]
Seems fair

**Comment by CyntexMore** [comment]
Here's a follow up.

If you successfully compiled and "injected" the kernel module and it bricked your kernel you can do the following to reinstall the kernel:

1. Get into emergency mode or chroot into the system via something like `archiso`;
2. Let your package manager reinstall the Linux kernel by itself, for example on Arch you could run `sudo pacman -Syy linux` (or any Linux kernel fork) **OR** just reinstall the kernel yourself;
3. Navigate to `/path/to/tmx-ffb-driver/src` and remove the `tmx_driver.ka` file so it won't load again, just to be sure;

I'll work on a fix as soon as possible.

**Comment by CyntexMore** [comment]
It seems like the issue is resolved (to be honest I don't know what solved it O-O) but I won't close the issue for now because the kernel module is very unstable and any commit could break it.

**Comment by CyntexMore** [comment]
It seems like the issue is fixed. If needed I'll reopen the issue in the future.
